version: '3'
services:
  app:
    build: 
      context: .
      args:
        - GOOGLE_CONFIG=${GOOGLE_CONFIG}
        - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    depends_on: 
      - postgres
    env_file:
      - .env
    ports:
      - "4390:4390"
    volumes:
      - .:/home/node/app
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin:/root/.pgadmin:rw
    ports:
      - "5050:80"
